### PR TITLE
Fix fsspec and s3fs dependencies

### PR DESCRIPTION
**Pull request by albertvillanova**
This PR:
- Adds explicit dependency on fsspec by using the tilde requirement because fsspec does not use semantic versioning.
- ~~Removes dependency on s3fs because this package is no longer used.~~
- ~~Sets s3fs as dev dependency (also using the tilde requirement) because 2 tests use it (see [comment](https://github.com/huggingface/dataset-viewer/pull/2671#issuecomment-2042277624) below)~~
- Sets the indirect dependence on s3fs through the extras of fsspec: `fsspec[s3]` (see [comment](https://github.com/huggingface/dataset-viewer/pull/2671#issuecomment-2043126529) and [comment](https://github.com/huggingface/dataset-viewer/pull/2671#issuecomment-2043149269) below)

### CODE REVIEW

**Comment by albertvillanova** [comment]
There is an underlying issue with dependencies: while `s3fs` is no longer used, tests do use `aiobotocore` but this dependency is not defined.

I am addressing this issue.

**Comment by albertvillanova** [comment]
There are 2 tests that use s3fs:
```
FAILED tests/test_integration_s3_cloudfront.py::test_real_cloudfront - ImportError: Install s3fs to access S3
FAILED tests/viewer_utils/test_features.py::test_ogg_audio_with_s3 - ImportError: Install s3fs to access S3
```

I add s3fs as dev dependency.

**Comment by severo** [comment]
would be good to run e2e locally to understand what is going wrong (don't forget to add secrets, like `S3_ACCESS_KEY_ID`, in `.env` and run `set -a && source .env && set +a &&  make e2e`)

**Comment by severo** [comment]
OK, for example:

```
docker logs -f e2e-api-1
```


```
INFO: 2024-04-08 15:58:22,785 - root - trying to initialize storage client with protocol='s3' storage_root='hf-datasets-server-statics-test/cached-assets' base_url='https://datasets-server-test.us.dev.moon.huggingface.tech/cached-assets' overwrite=False
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/src/services/api/.venv/lib/python3.9/site-packages/fsspec/registry.py", line 235, in get_filesystem_class
    register_implementation(protocol, _import_class(bit["class"]))
  File "/src/services/api/.venv/lib/python3.9/site-packages/fsspec/registry.py", line 270, in _import_class
    mod = importlib.import_module(mod)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 's3fs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/src/services/api/.venv/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/src/services/api/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/src/services/api/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/src/services/api/.venv/lib/python3.9/site-packages/uvicorn/config.py", line 483, in load
    self.loaded_app = self.loaded_app()
  File "/src/services/api/src/api/app.py", line 30, in create_app
    return create_app_with_config(app_config=app_config, endpoint_config=endpoint_config)
  File "/src/services/api/src/api/app.py", line 58, in create_app_with_config
    cached_assets_storage_client = StorageClient(
  File "/src/libs/libcommon/src/libcommon/storage_client.py", line 54, in __init__
    self._fs = fsspec.filesystem(
  File "/src/services/api/.venv/lib/python3.9/site-packages/fsspec/registry.py", line 289, in filesystem
    cls = get_filesystem_class(protocol)
  File "/src/services/api/.venv/lib/python3.9/site-packages/fsspec/registry.py", line 237, in get_filesystem_class
    raise ImportError(bit["err"]) from e
ImportError: Install s3fs to access S3
```

**Comment by severo** [comment]
Same error for:
- services/admin
- services/api
- services/worker
- services/rows
- services/search

Not:
- services/sse-api

**Comment by albertvillanova** [comment]
Thanks a lot for the investigation, @severo, and for the hints on how to debug this case: I take note.

I misunderstood the dependence on s3fs because this is not explicit in the code, but through the passed argument to `fsspec.filesystem`...

I would propose:
- Restore the dependence on s3fs, as the main target of this PR was just to explicitly depend on fsspec
  - Maybe this can be donem as you suggested, through `fsspec[s3]`: I am investigating this
- Leave for a subsequent issue/PR to check whether it is possible to make explicit in the code the dependence on s3fs

**Review by albertvillanova — COMMENTED** [review]
@severo CI has passed now.

**Review by severo — APPROVED** [review]

**Comment by albertvillanova** [comment]
I merged main to fix conflicts. I will merge this PR once CI has passed.

**Pull request merged**
