### PR TITLE
Support `Sequence()` features in Croissant crumbs.

### PR DESCRIPTION
**Pull request by marcenacp**
WIP: still checking that it works as intended on mlcroissant side.

### CODE REVIEW

**Review by lhoestq — COMMENTED** [review]
Btw here are some useful info:
- Sequence(Value("float32")) does represent a sequence of float32 BUT similar to TFDS, Sequence({"foo": Value("float32")}) represents a dictionary in the form {"foo": [...]} containing float32 values
- because of that, [Value("float32")] is equivalent to Sequence(Value("float32")), and [{"foo": Value("float32")}] is NOT equivalent to Sequence({"foo": Value("float32")})

**Comment by marcenacp** [comment]
@lhoestq Thanks for the clarification! I changed my code to handle both `Sequence(Value("float32"))` and `[Value("float32")]`. I don't handle the cases of dicts for now.

**Comment by marcenacp** [comment]
@lhoestq I don't have an easy way to launch the tests locally. Can you trigger them on the PR? Thanks :)

**Comment by marcenacp** [comment]
@lhoestq I shouldn't have amended my commit. Now it's asking for the approval again. Can you please trigger the workflows again? I'll make sure to push new commits instead of amending next time.

**Comment by lhoestq** [comment]
cool ! feel free to run `make style` to fix the code formatting issue

**Comment by marcenacp** [comment]
@lhoestq Done. There's still errors but unrelated to my changes, should I also change those? Thanks!

**Comment by marcenacp** [comment]
@lhoestq Quentin, pinging you again to trigger the workflows. 🤞

**Comment by marcenacp** [comment]
PS: I couldn't follow the DEVELOPER_GUIDE. `poetry` hangs at the very beginning and never finishes, so I ended up using pip manually.

**Comment by lhoestq** [comment]
haha should be good now ! x) sorry for the inconvenience of this process

**Comment by marcenacp** [comment]
It's green... except for the e2e tests. Is this normal? Once merged, when does it get deployed to https://huggingface.co/api/datasets? Thanks again!

**Comment by lhoestq** [comment]
I'll deploy this afternoon if it's ok for you

**Pull request merged**
