### PR TITLE
bump croissant job version

### PR DESCRIPTION
**Pull request by lhoestq**
cc @ccl-core this way all the croissant-crumbs will be updated with the latest changes

### CODE REVIEW

**Comment by ccl-core** [comment]
Thank you a lot Quentin! That's great news 🥐

**Comment by lhoestq** [comment]
Hey @ccl-core ! All the croissant metadata are updated and it all went well :)

It's minor, but I received a notification only about two errors on those datasets from the Google Search Console:
- https://huggingface.co/datasets/maartensap/ToxicityPrompts
- https://huggingface.co/datasets/DATEXIS/Wiki-ICD10

It's not a big deal but it looks like their croissant metadata are too long to be indexed, but let me know

```
Parsing error: Missing'; or '}'
Items with this issue are invalid. Invalid items are not eligible for Google Search's rich results
```

**Comment by ccl-core** [comment]
Thank you @lhoestq ! I'm having a look.

**Comment by ccl-core** [comment]
Hi @lhoestq , this might help reducing the size of our croissant definitions: https://github.com/huggingface/dataset-viewer/pull/3106

We wouldn't loose much, as those names are the same as the ids, and most of the descriptions were containing redundant information anyways. In the case of datasets with a lot of fields, such as the ones you posted above, this results in considerable size reduction.

Note that since releasing Croissant 1.0 we are now using ids instead of names in mlcroissant, so we are able to parse the new, shorter croissants wihtout any change needed for mlcroissant.

Let us know if you have any further comments or observations :)

**Comment by lhoestq** [comment]
I see, thanks for investigating and for removing redundant info :)

**Pull request merged**
