### PR TITLE
[Croissant] Update `data` field in new splits recordset

### PR DESCRIPTION
**Pull request by ccl-core**

### CODE REVIEW

**Comment by ccl-core** [comment]
@lhoestq @severo could you PTAL? Thanks!

**Comment by ccl-core** [comment]
Follow-up to https://github.com/huggingface/dataset-viewer/pull/3058

**Review by lhoestq — APPROVED** [review]

**Comment by ccl-core** [comment]
Thanks @lhoestq -- do you know how long it will take for this to be deployed more or less? I remember it took a few days for https://github.com/huggingface/dataset-viewer/pull/3058, any chance we could speed the process up a bit for this PR?

**Comment by lhoestq** [comment]
I'm aiming for a deploy later today - will ping you once it's done

**Comment by lhoestq** [comment]
deployed ! :)

**Comment by ccl-core** [comment]
Merciii!

**Comment by ccl-core** [comment]
Hi @lhoestq ! We were wondering how long it might take before all datasets' croissants include this change?

We noticed that some of them, like e.g. https://huggingface.co/api/datasets/ai4bharat/sangraha/croissant, seem to still use `split_name` instead of `split_record_set_name/split_name` in the split recordset's `"data"` field.

**Pull request merged**
