### PR TITLE
doc: Read parquet files with PySpark 

### PR DESCRIPTION
**Pull request by AndreaFrancis**
Adding primary doc for reading parquet files with PySpark

### CODE REVIEW

**Review by lhoestq — COMMENTED** [review]
Cool ! Maybe put links to files in the repo rather than from the API which is more advanced usage ? This way people can read parquet, jsonl and more

**Comment by AndreaFrancis** [comment]
> Cool ! Maybe put links to files in the repo rather than from the API which is more advanced usage ? This way people can read parquet, jsonl and more

Agree, but I wanted to follow the same pattern as the other sections (ClickHouse, cuDF, DuckDB, Pandas, and Polars), which point to refs/convert/parquet.

Additionally, it will be in the `Query datasets from Dataset Viewer API` section specifically.

**Comment by lhoestq** [comment]
Ah yes sorry, this is the viewer's docs so yea it should show the viewer's parquet files

**Review by lhoestq — APPROVED** [review]
LGTM ! Would be cool to have spark docs in the hub docs as well !

**Pull request merged**
