### PR TITLE
Update datasets 2.19.1 with hotfix to shorten long logs

### PR DESCRIPTION
**Pull request by albertvillanova**
Update datasets 2.19.1 with hotfix to shorten long logs.

### CODE REVIEW

**Review by lhoestq — APPROVED** [review]
Thanks ! Feel free to merge when the merge conflicts are fixed

**Comment by albertvillanova** [comment]
There is an incompatibility after the merge of:
- #2781

When I try to lock the poetry files, I get:
> Because huggingface-hub[hf-transfer] (0.20.0.dev0) @ git+https://github.com/huggingface/huggingface_hub.git@657a1bdcc0545309463e8651f62010154e9b3792 depends on huggingface-hub (0.20.0.dev0) @ git+https://github.com/huggingface/huggingface_hub.git@657a1bdcc0545309463e8651f62010154e9b3792
 and datasets[audio,vision] (2.19.1) @ git+https://github.com/huggingface/datasets.git@3638183e2f7e0dce8924e46e7cc21bf6d5d7adfb depends on huggingface-hub (>=0.21.2), huggingface-hub[hf-transfer] (0.20.0.dev0) @ git+https://github.com/huggingface/huggingface_hub.git@657a1bdcc0545309463e8651f62010154e9b3792 is incompatible with datasets[audio,vision] (2.19.1) @ git+https://github.com/huggingface/datasets.git@3638183e2f7e0dce8924e46e7cc21bf6d5d7adfb.
And because libcommon (0.6.8) @ file:///home/albert/projects/forks/huggingface/datasets-server/libs/libcommon depends on datasets[audio,vision] (2.19.1) @ git+https://github.com/huggingface/datasets.git@3638183e2f7e0dce8924e46e7cc21bf6d5d7adfb, huggingface-hub[hf-transfer] (0.20.0.dev0) @ git+https://github.com/huggingface/huggingface_hub.git@657a1bdcc0545309463e8651f62010154e9b3792 is incompatible with libcommon (0.6.8) @ file:///home/albert/projects/forks/huggingface/datasets-server/libs/libcommon.
So, because cache-maintenance depends on libcommon (0.6.8) @ file:///home/albert/projects/forks/huggingface/datasets-server/libs/libcommon which depends on huggingface-hub[hf-transfer] (0.20.0.dev0) @ git+https://github.com/huggingface/huggingface_hub.git@657a1bdcc0545309463e8651f62010154e9b3792, version solving failed.

**Comment by albertvillanova** [comment]
I get the same issue even on the main branch:
```shell
git checkout main
cd jobs/cache_maintenance
poetry@1.8.2 lock --no-update
```

Do you have the same issue?

**Comment by albertvillanova** [comment]
Apparently, it was an issue with my local Python environments.

I deleted my .venv directories and then I locked the poetry files with success.

**Pull request merged**
