### PR TITLE
Update datasets to 2.19.0 and fsspec to 2024.3.1

### LINKED ISSUE #2739: Update datasets to 2.19.0
Update datasets to 2.19.0: https://github.com/huggingface/datasets/releases/tag/2.19.0

### PR DESCRIPTION
**Pull request by albertvillanova**
Update datasets to 2.19.0.

Fix #2739.

### CODE REVIEW

**Comment by albertvillanova** [comment]
Tests for worker are not passing: https://github.com/huggingface/dataset-viewer/actions/runs/8753796799/job/24024224560?pr=2740

I am fixing it.

**Comment by albertvillanova** [comment]
As @mariosasko and @lhoestq suggested (see https://github.com/huggingface/datasets/pull/6704#discussion_r1572601670 and https://github.com/huggingface/datasets/pull/6704#discussion_r1572699470), I am fixing the issue by creating a new variable by joining the 2 new ones).

**Comment by albertvillanova** [comment]
@lhoestq, I have just checked that the fix is not as direct as suggested.

Before the changes introduced by @mariosasko in https://github.com/huggingface/datasets/pull/6704, the ImportError was not raised if fsspec version was < 2023.12.0, i.e. the pattern NON_WORD_GLOB_SEPARATOR is present in ALL KEYWORDS_IN_PATH_NAME_BASE_PATTERNS for both cases fsspec < 2023.9.0 or fsspec < 2023.12.0.
That means the ImportError was only raised if fsspec >= 2023.12.0.

But after the changes introduced by @mariosasko in https://github.com/huggingface/datasets/pull/6704, if we join the variables KEYWORDS_IN_DIR_NAME_BASE_PATTERNS and KEYWORDS_IN_FILENAME_BASE_PATTERNS, the ImportError will always be raised: there is always at least one pattern that does not contain the NON_WORD_GLOB_SEPARATOR, for example:
- for fsspec < 2023.9.0:
  - filename = "{keyword}[{sep}]*"
  - firname = "{keyword}/**"
- for fsspec < 2023.12.0:
  - filename = "{keyword}[{sep}]*"
  - dirname = "{keyword}/**/*"
- for fsspec >= 2023.12.0: any of the filenames or dirnames

**Comment by albertvillanova** [comment]
@lhoestq if you are trying to put a constraint on the version of fsspec, wouldn't it be easier to check the installed version?

**Comment by lhoestq** [comment]
Then we need to update `NON_WORD_GLOB_SEPARATOR`, I can continue this PR

**Comment by lhoestq** [comment]
thanks !

**Pull request merged**
