### PR TITLE
Use hf_transfer in e2e and align huggingface-hub version

### PR DESCRIPTION
**Pull request by albertvillanova**
Use hf_transfer in e2e and align huggingface-hub version with that used in the rest of libs/services.

Note that hf_transfer was already enabled in e2e (by setting the corresponding HF_HUB_ENABLE_HF_TRANSFER env variable) by PR:
- #2615
  - See: https://github.com/huggingface/dataset-viewer/pull/2615/files#diff-783dde1612e57c909ba25c842f48f55671ff9eee75352951d60a90e3f59dec48R69

This PR adds it as a dependency, so that it is properly installed in e2e tests.

CC: @AndreaFrancis

### CODE REVIEW

**Comment by severo** [comment]
hmmm in e2e tests, huggingface_hub is only used to upload files to the hub-ci. I'm not sure installing hf_transfer is required (e2e is not related to the other services, which are built in docker images with all the required packages already).

**Comment by albertvillanova** [comment]
Yes, exactly, it is just used to upload files to hub-cli.

**Comment by AndreaFrancis** [comment]
Sorry, it was my mistake; it should not be necessary to set the HF_HUB_ENABLE_HF_TRANSFER in an e2e-related environment.
Removing these lines of code should remove the usage of it in the e2e execution:
https://github.com/huggingface/dataset-viewer/pull/2615/files#diff-783dde1612e57c909ba25c842f48f55671ff9eee75352951d60a90e3f59dec48R69
https://github.com/huggingface/dataset-viewer/pull/2615/files#diff-2577dc7dd20ba506a083636a88fc3a51d1b3e7b60bc642adcd1b94f882441711R49

It should still work since the flag is already set on the Dockerfiles for the worker and search services.

**Comment by AndreaFrancis** [comment]
> it should not be necessary to set the HF_HUB_ENABLE_HF_TRANSFER in an e2e-related environment.

I sent https://github.com/huggingface/dataset-viewer/pull/2727 to remove it from e2e

**Comment by AndreaFrancis** [comment]
https://github.com/huggingface/dataset-viewer/pull/2727 is merge, now we dont need hf_transfer extra in the e2e project.

**Comment by albertvillanova** [comment]
I am closing this PR. as you don't see the interest of using hf_transfer to upload files to the hub-ci.

**Pull request closed without merging**
