### PR TITLE
move the docs page

### PR DESCRIPTION
**Pull request by severo**
This change should move https://huggingface.co/docs/datasets-server to https://huggingface.co/docs/dataset-viewer.

cc @mishig25: we also need to redirect https://huggingface.co/docs/datasets-server to https://huggingface.co/docs/dataset-viewer. Where do we do it?

### CODE REVIEW

**Comment by mishig25** [comment]
this file need to be changed too https://github.com/huggingface/dataset-viewer/blob/main/.github/workflows/doc-pr-build.yml

**Comment by mishig25** [comment]
to changes these lines as well https://github.com/huggingface-internal/moon-landing/blob/94daef6d9d6c77c70b23de6a0612dd1d93ea0978/server/views/pages/DocsPage/consts.ts#L256-L258

**Review by julien-c — APPROVED** [review]
lgtm

**Comment by severo** [comment]
OK, let's go!

**Pull request merged**
