### PR TITLE
Add Polars loading code

### PR DESCRIPTION
**Pull request by nameexhaustion**
Hello from the Polars team! We've recently added support for scanning Hugging Face datasets, and to make it easier for users we're hoping that Polars code snippets could be added under the "Use this dataset" section on the dataset viewer webpage, next to the other libraries.

Specifically, here's where we'd like to add Polars as an option:
image

### CODE REVIEW

**Review by lhoestq — COMMENTED** [review]
Cool thanks ! Excited to see Polars as an option on HF :)

When login is required, we show this message for Pandas and Dask, and I think we can show the same message for Polars no (if Polars supports reading the user token from disk) ?

```python
# Login using e.g. `huggingface-cli login` to access this dataset
```

(the token is stored in `~/.cache/huggingface/token` where `~/.cache/huggingface` is the default `HF_HOME`)

There will be a link in the UI anyway to the Polars docs on HF where we can explain other authentication, methods like `storage_options`.

If this authentication method is not implemented yet in Polars I'm happy to leave it as is :)

**Comment by nameexhaustion** [comment]
> (the token is stored in ~/.cache/huggingface/token where ~/.cache/huggingface is the default HF_HOME)

Ah, I haven't seen this one before. Thanks for the explanation - I'll see if I can get some support in for this.

**Comment by nameexhaustion** [comment]
Updated to show the `LOGIN_COMMENT` message

**Review by lhoestq — APPROVED** [review]
LGTM ! cc @severo for viz

**Comment by severo** [comment]
Nice, thanks!

I opened https://github.com/huggingface/huggingface.js/pull/822. And then, I'll update the Hub's code

**Pull request merged**
