### PR TITLE
Adding large_string to duckdb-index worker and tests

### PR DESCRIPTION
**Pull request by AndreaFrancis**
Fix for https://github.com/huggingface/dataset-viewer/issues/2613

### CODE REVIEW

**Review by severo — APPROVED** [review]

**Comment by severo** [comment]
The idea is to recompute the datasets manually, right? I imagine that only few datasets use this type.

**Comment by AndreaFrancis** [comment]
> The idea is to recompute the datasets manually, right? I imagine that only few datasets use this type.

Yes, I will put here the datasets that were refreshed when it is ready.

**Comment by severo** [comment]
(the number is enough... better not to give the names, as some might be private)

**Comment by AndreaFrancis** [comment]
I will refresh 3364 splits; the logic is:  Get all datasets with "text" modality and intersect with the list of splits with "has_fts": false.

**Comment by severo** [comment]
OK. Maybe some datasets have both string and large_string: we will not refresh them, right? Is it a way to find them too? I think the answer is no, without scanning every "/info" response

**Comment by AndreaFrancis** [comment]
> OK. Maybe some datasets have both string and large_string: we will not refresh them, right? Is it a way to find them too? I think the answer is no, without scanning every "/info" response

In case they had both (string and large_string), they should already be "has_fts": true, so there should be no refresh for them.

**Pull request merged**
