### PR TITLE
Update datasets to 2.21.0

### LINKED ISSUE #3024: Upgrade to datasets@2.21.0
https://github.com/huggingface/datasets/releases/tag/2.21.0

When done, we should refresh some datasets, like https://huggingface.co/datasets/ProGamerGov/synthetic-dataset-1m-dalle3-high-quality-captions/discussions/1#66bcd7e2f1685a3ade2e55f5

### PR DESCRIPTION
**Pull request by albertvillanova**
Update datasets to 2.21.0.

Fix #3024.

### CODE REVIEW

**Comment by albertvillanova** [comment]
The are errors in the CI tests.

I guess at least some of them are related to the change in the Hub in relation with gated datasets:
- huggingface/datasets#7109

I am updating huggingface-hub.

**Comment by albertvillanova** [comment]
I have decided to update first to datasets-2.20.0 and check all CI tests pass:
- #3040

Afterwards, we can merge main to this PR and see the CI tests: if there is a bug in datasets-2.21.0, we could make a patch release and update to datasets-2.21.1 instead.

**Comment by albertvillanova** [comment]
I am resolving the conflicts of this PR.

I think we could merge it and then I could update to dataset 3.0 and see if something new is broken...

**Review by lhoestq — APPROVED** [review]
ok !

**Pull request merged**
