### PR TITLE
Docs: mention partial parquet conversion for big row groups

### PR DESCRIPTION
**Pull request by lhoestq**
asked at https://huggingface.slack.com/archives/C0709MK0PUN/p1720433431019569?thread_ts=1720210655.175099&cid=C0709MK0PUN

### CODE REVIEW

**Comment by julien-c** [comment]
note that this should ideally be displayed directly on the hub in the cases when it happens, imo

**Review by severo — APPROVED** [review]

**Comment by lhoestq** [comment]
> note that this should ideally be displayed directly on the hub in the cases when it happens, imo

maybe in the (i) ?

image

Something like "The table contains 100 rows per page, up to 5GB. It is loaded from converted Parquet files, since original files have row group sizes bigger than the recommended value (100-300MB uncompressed)"

**Comment by severo** [comment]
I imagine that we can detect the case, if:
- the viewer is partial
- the dataset has the "parquet" file format

We might want to show the warning in the right column (where we show the size tags)

Capture d’écran 2024-07-10 à 10 47 52

text:

> ⚠️ The original Parquet files have row group sizes bigger than the recommended value (100-300MB uncompressed). The dataset viewer falls back to auto-converted Parquet files on the first 5GB of raw data.

**Comment by lhoestq** [comment]
Yes you can indeed detect the case like that.

Not a big fan of the warning which can get a lot of the user's attention. Here is my suggestion for the text: 

> ⓘ The Viewer and auto-converted Parquet files contain data up to 5GB, since original files have row groups that are too big to be displayed. The recommended row group size is 100-300MB in-memory.

**Comment by severo** [comment]
I created https://github.com/huggingface-internal/moon-landing/pull/10644. Not sure if it's the best way to do. Let's discuss there

**Pull request merged**
